"use client";
import {useEffect,useRef,useState} from "react";
import * as THREE from "three";
import {RoundedBoxGeometry} from "three/addons/geometries/RoundedBoxGeometry.js";

const initial=[{name:"Energía",value:74,color:"#76b7b2",icon:"⚡"},{name:"Hambre",value:61,color:"#e9ad62",icon:"●"},{name:"Higiene",value:82,color:"#72a9d8",icon:"◈"},{name:"Diversión",value:55,color:"#d080a7",icon:"★"}];
function box(s:THREE.Scene,z:[number,number,number],p:[number,number,number],c:number,n=""){const radius=Math.min(.1,Math.min(...z)*.18),m=new THREE.Mesh(new RoundedBoxGeometry(...z,3,radius),new THREE.MeshStandardMaterial({color:c,roughness:.68}));m.position.set(...p);m.castShadow=m.receiveShadow=true;m.name=n;s.add(m);return m}
function cyl(s:THREE.Scene,r:number,h:number,p:[number,number,number],c:number,n=""){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,24),new THREE.MeshStandardMaterial({color:c,roughness:.65}));m.position.set(...p);m.castShadow=true;m.name=n;s.add(m);return m}

export default function Home(){
 const mount=useRef<HTMLDivElement>(null),actRef=useRef<(x:string)=>void>(()=>{});const [needs,setNeeds]=useState(initial),[action,setAction]=useState("Nada pendiente"),[clock,setClock]=useState("09:42"),[paused,setPaused]=useState(false),[creator,setCreator]=useState(true),[avatar,setAvatar]=useState({name:"Alex",body:"adulto",skin:"#b97855",hair:"#37271f",shirt:"#315f79",pants:"#27384b"});
 const control=useRef({paused:false,creator:true});control.current={paused,creator};
 const act=(kind:string)=>actRef.current(kind);
 useEffect(()=>{const host=mount.current;if(!host)return;const scene=new THREE.Scene();scene.background=new THREE.Color(0x9ec7d0);scene.fog=new THREE.Fog(0x9ec7d0,25,44);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.appendChild(renderer.domElement);const camera=new THREE.OrthographicCamera(-10,10,7,-7,.1,100);camera.position.set(15,17,18);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight(0xfff6df,0x4d6972,2.5));const sun=new THREE.DirectionalLight(0xfff0cf,3.3);sun.position.set(-8,16,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
 const floor=box(scene,[15,.35,11],[0,-.22,0],0xd6bd92);for(let i=-7;i<=7;i++)box(scene,[.035,.02,10.5],[i,-.035,0],0xb59b76);box(scene,[.25,4.5,11],[-7.45,2.1,0],0xf1dfc4);box(scene,[15,4.5,.25],[0,2.1,-5.45],0xead7bc);
 box(scene,[5.2,.06,3.4],[2,.04,1.1],0x557d7b);box(scene,[4.4,.75,1.35],[3.5,.55,3.2],0xc89066);box(scene,[4.4,.8,.32],[3.5,1.15,3.72],0xb67854);box(scene,[2.5,.22,1.25],[2,.35,.55],0x9b6c43);for(const x of [1.05,2.95])box(scene,[.18,.6,.18],[x,.12,.15],0x604430);
 box(scene,[3.7,.45,1.05],[2,.65,-3.92],0x73563e);const tv=box(scene,[3.25,2.05,.28],[2,1.9,-4.18],0x24272d,"tv");box(scene,[2.75,1.5,.03],[2,1.9,-4.02],0x315d71,"tv");
 for(const [z,p,c] of [[[5.1,.55,3.25],[-4.25,.4,2.7],0x815942],[[4.75,.65,2.85],[-4.25,.82,2.7],0xdbc8a5],[[4.75,.22,1.65],[-4.25,1.15,3.3],0xb86554],[[1.6,.3,.78],[-4.25,1.36,3.72],0xf2e7d3]] as const)box(scene,[...z],[...p],c,"bed");box(scene,[1.3,1.7,1.2],[-6.25,.85,.6],0x73513c);box(scene,[1.3,.08,1.2],[-6.25,1.74,.6],0xd6b873);
 box(scene,[5.2,.08,3.35],[-4.65,.02,-3.45],0xbad0cf);box(scene,[.18,3.5,3.6],[-2.12,1.7,-3.62],0xe4ece8);box(scene,[1.5,1.05,.18],[-6.5,.5,-1.7],0xe4ece8);box(scene,[2.2,1.05,.18],[-3.22,.5,-1.7],0xe4ece8);box(scene,[2.15,.2,1.7],[-5.75,.12,-4.25],0xf4f6f2,"shower");const glass=new THREE.Mesh(new THREE.BoxGeometry(.06,2.7,1.8),new THREE.MeshPhysicalMaterial({color:0xbfe0e5,transparent:true,opacity:.35,roughness:.1}));glass.position.set(-4.68,1.4,-4.2);glass.name="shower";scene.add(glass);cyl(scene,.09,2.3,[-6.65,1.25,-4.9],0xb4b8b5,"shower");const shower=cyl(scene,.38,.08,[-6.3,2.35,-4.9],0xb4b8b5,"shower");shower.rotation.z=Math.PI/2;
 box(scene,[1.05,.48,1.15],[-3.25,.35,-4.35],0xf4f2e9,"toilet");cyl(scene,.53,.48,[-3.25,.65,-4.12],0xf4f2e9,"toilet");box(scene,[1.2,1.05,.35],[-3.25,1.05,-5.02],0xf4f2e9,"toilet");box(scene,[1.35,.25,.85],[-3.15,1.05,-2.35],0xf5f2e9,"sink");cyl(scene,.12,.95,[-3.15,.52,-2.35],0xb9b5aa);box(scene,[1.5,1.3,.08],[-3.15,2.05,-1.82],0x91b8bd);box(scene,[2.3,1.9,.18],[-2.7,2.5,-5.27],0x6f5241);box(scene,[1.9,1.5,.03],[-2.7,2.5,-5.38],0xe4b663);
 cyl(scene,.48,.55,[6.3,.3,-4.25],0x9d6c4e);for(let i=0;i<7;i++){const l=new THREE.Mesh(new THREE.SphereGeometry(.22,12,8),new THREE.MeshStandardMaterial({color:0x4f8056}));l.scale.set(.7,2,.45);l.position.set(6.3+Math.sin(i)*.45,1+Math.cos(i*.8)*.35,-4.25+Math.cos(i)*.4);l.rotation.z=Math.sin(i)*.7;scene.add(l)}
 box(scene,[3.8,.9,.72],[4.9,.46,-2.05],0xb6c5b7);box(scene,[1.45,2.85,.82],[6.35,1.45,-2.08],0xe8e7dc);box(scene,[1.15,1.65,.05],[6.35,1.75,-1.65],0xc4d5d7);box(scene,[1.8,.92,.75],[3.05,.47,-2.05],0x8fa78f);cyl(scene,.32,.08,[3.05,.97,-2.15],0x31383b);box(scene,[.7,.12,.5],[5.05,.98,-2.1],0x30383a);for(const x of [3.8,4.9,5.8])box(scene,[.025,.5,.03],[x,.48,-1.66],0x6f8075);
 cyl(scene,1.05,.18,[5.15,.72,.25],0xa77a54);cyl(scene,.16,1.25,[5.15,.16,.25],0x604a37);for(const [x,z] of [[4.1,.25],[6.2,.25],[5.15,-.82],[5.15,1.32]]){box(scene,[.72,.15,.72],[x,.48,z],0xc38c62);cyl(scene,.1,.88,[x,.04,z],0x6e4c36)}
 box(scene,[3.1,1.65,.1],[3.6,2.8,-5.27],0xf4ead8);box(scene,[2.55,1.18,.035],[3.6,2.8,-5.20],0x86b7c2);box(scene,[.08,1.18,.05],[3.6,2.8,-5.16],0xe9f1ef);box(scene,[2.55,.07,.05],[3.6,2.8,-5.16],0xe9f1ef);cyl(scene,.5,.35,[.2,2.9,.1],0xe5c981);cyl(scene,.04,2.6,[.2,1.45,.1],0x544d45);const warm=new THREE.PointLight(0xffd89b,18,8);warm.position.set(.2,2.7,.1);scene.add(warm);
 const person=new THREE.Group();person.position.set(0,0,2);const skinMat=new THREE.MeshStandardMaterial({color:avatar.skin,roughness:.62}),shirtMat=new THREE.MeshStandardMaterial({color:avatar.shirt,roughness:.72}),pantsMat=new THREE.MeshStandardMaterial({color:avatar.pants,roughness:.8}),hairMat=new THREE.MeshStandardMaterial({color:avatar.hair,roughness:.9});const torso=new THREE.Mesh(new THREE.CapsuleGeometry(avatar.body==="atlético"?.44:.4,.72,8,18),shirtMat);torso.position.y=1.38;torso.scale.set(1,1,avatar.body==="delgado"?.78:.92);person.add(torso);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.16,.18,.22,18),skinMat);neck.position.y=1.92;person.add(neck);const head=new THREE.Mesh(new THREE.SphereGeometry(.36,32,24),skinMat);head.scale.set(.92,1.12,.94);head.position.y=2.25;person.add(head);const nose=new THREE.Mesh(new THREE.ConeGeometry(.065,.16,16),skinMat);nose.rotation.x=Math.PI/2;nose.position.set(0,2.25,.36);person.add(nose);for(const x of [-.13,.13]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.032,12,8),new THREE.MeshStandardMaterial({color:0x1b2529}));eye.position.set(x,2.32,.337);person.add(eye)}const hair=new THREE.Mesh(new THREE.SphereGeometry(.375,28,16,0,Math.PI*2,0,Math.PI*.52),hairMat);hair.scale.set(.94,1.1,.96);hair.position.y=2.32;person.add(hair);const hips=new THREE.Mesh(new THREE.BoxGeometry(.62,.32,.36),pantsMat);hips.position.y=.92;person.add(hips);const legs:THREE.Group[]=[],arms:THREE.Group[]=[];for(const x of [-.2,.2]){const leg=new THREE.Group();leg.position.set(x,.82,0);const upper=new THREE.Mesh(new THREE.CapsuleGeometry(.105,.48,6,12),pantsMat);upper.position.y=-.28;leg.add(upper);const shoe=new THREE.Mesh(new THREE.BoxGeometry(.24,.17,.42),new THREE.MeshStandardMaterial({color:0x3a332e}));shoe.position.set(0,-.68,.1);leg.add(shoe);person.add(leg);legs.push(leg)}for(const x of [-.55,.55]){const arm=new THREE.Group();arm.position.set(x,1.66,0);const limb=new THREE.Mesh(new THREE.CapsuleGeometry(.09,.56,6,12),shirtMat);limb.position.y=-.3;arm.add(limb);const hand=new THREE.Mesh(new THREE.SphereGeometry(.105,16,12),skinMat);hand.position.y=-.68;arm.add(hand);person.add(arm);arms.push(arm)}const plumb=new THREE.Mesh(new THREE.OctahedronGeometry(.28),new THREE.MeshStandardMaterial({color:0x6bd870,emissive:0x163b18}));plumb.scale.y=1.75;plumb.position.y=3.25;person.add(plumb);person.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true});scene.add(person);
 // Navigation uses floor-space obstacles expanded by the character radius.
 const solids=scene.children.filter(o=>o instanceof THREE.Mesh&&o!==floor&&o!==glass&&o!==shower&&o.position.y>.1&&o.position.y<2&& !['bed','toilet'].includes(o.name));
 const bounds=solids.map(o=>new THREE.Box3().setFromObject(o)).filter(b=>b.min.y<1.6&&b.max.y>.3);
 bounds.push(new THREE.Box3(new THREE.Vector3(-6.8,0,1.075),new THREE.Vector3(-1.7,2,4.325)));
 bounds.push(new THREE.Box3(new THREE.Vector3(-3.8,0,-5.2),new THREE.Vector3(-2.7,2,-3.58)));
 bounds.push(new THREE.Box3(new THREE.Vector3(-4.74,0,-5.1),new THREE.Vector3(-4.62,3,-3.3)));
 const blocked=(x:number,z:number)=>x< -6.95||x>6.95||z< -4.95||z>4.95||bounds.some(b=>x>b.min.x-.3&&x<b.max.x+.3&&z>b.min.z-.3&&z<b.max.z+.3);
 const step=.2, width=71,depth=51;
 const point=(i:number)=>new THREE.Vector3(-7+(i%width)*step,0,-5+Math.floor(i/width)*step);
 const free=Array.from({length:width*depth},(_,i)=>{const p=point(i);return !blocked(p.x,p.z)});
 const nearest=(v:THREE.Vector3)=>{let best=-1,dist=Infinity;for(let i=0;i<free.length;i++){if(!free[i])continue;const p=point(i),d=(v.x-p.x)**2+(v.z-p.z)**2;if(d<dist){dist=d;best=i}}return best};
 const route=(from:THREE.Vector3,to:THREE.Vector3)=>{const start=nearest(from),end=nearest(to),prev=new Int32Array(free.length).fill(-1),queue=[start];prev[start]=start;for(let q=0;q<queue.length&&prev[end]<0;q++){const i=queue[q];for(const n of [i-1,i+1,i-width,i+width]){if(n<0||n>=free.length||!free[n]||prev[n]>=0||Math.abs(n%width-i%width)>1)continue;prev[n]=i;queue.push(n)}}if(prev[end]<0)return null;const result:THREE.Vector3[]=[];for(let i=end;i!==start;i=prev[i])result.push(point(i));return result.reverse()};
 const specs:Record<string,{approach:THREE.Vector3;pose:THREE.Vector3;need:number;label:string;duration:number}>={
 bed:{approach:new THREE.Vector3(-4.3,0,.4),pose:new THREE.Vector3(-4.3,1.5,1.25),need:0,label:'Durmiendo',duration:18},
 tv:{approach:new THREE.Vector3(.65,0,3.2),pose:new THREE.Vector3(1.9,.55,3.12),need:3,label:'Viendo televisión',duration:16},
 shower:{approach:new THREE.Vector3(-5.5,0,-3),pose:new THREE.Vector3(-5.7,.23,-4.1),need:2,label:'Duchándose',duration:12},
 toilet:{approach:new THREE.Vector3(-4.25,0,-3.1),pose:new THREE.Vector3(-3.25,.25,-4.05),need:4,label:'Usando el baño',duration:9},
 eat:{approach:new THREE.Vector3(1.3,0,-2),pose:new THREE.Vector3(1.3,0,-2),need:1,label:'Comiendo',duration:10}
 };
 let values=[74,61,82,55,70],path:THREE.Vector3[]=[],task='',phase='idle',elapsed=0,decisionIn=1,uiTime=0,gameTime=582,walkTime=0;
 const restore=()=>{if(phase==='using'&&specs[task])person.position.copy(point(nearest(specs[task].approach)));person.rotation.set(0,0,0);person.position.y=0;for(const limb of [...legs,...arms])limb.rotation.set(0,0,0);plumb.visible=true};
 const command=(kind:string)=>{if(!specs[kind])return;restore();const next=route(person.position,specs[kind].approach);if(next===null){phase='idle';task='';setAction('No hay un camino libre');return}task=kind;path=next;phase='walking';elapsed=0;setAction('Yendo a '+({bed:'la cama',tv:'ver televisión',shower:'la ducha',toilet:'el baño',eat:'comer'}[kind]));};
 actRef.current=command;
 const tvScreen=box(scene,[2.85,1.65,.035],[2,1.9,-4.01],0x17212b,'tv');const screenMat=tvScreen.material as THREE.MeshStandardMaterial;
 const drops=new THREE.Group();scene.add(drops);for(let i=0;i<30;i++){const d=new THREE.Mesh(new THREE.SphereGeometry(.025,6,4),new THREE.MeshBasicMaterial({color:0x98d6f6,transparent:true,opacity:.65}));d.scale.y=4;d.position.set(-6.3+Math.random()*.7,Math.random()*2.4,-4.7+Math.random()*.7);drops.add(d)}drops.visible=false;
 const ray=new THREE.Raycaster(),pt=new THREE.Vector2();const click=(e:PointerEvent)=>{if(control.current.creator||control.current.paused)return;const r=renderer.domElement.getBoundingClientRect();pt.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);ray.setFromCamera(pt,camera);const hits=ray.intersectObjects(scene.children,true);const object=hits.find(h=>specs[h.object.name]);if(object){command(object.object.name);return}const h=ray.intersectObject(floor)[0];if(!h||blocked(h.point.x,h.point.z))return;restore();const next=route(person.position,h.point);if(next){path=next;task='';phase='walking';setAction('Caminando')}};
 renderer.domElement.addEventListener('pointerdown',click);
 const resize=()=>{const w=host.clientWidth,h=host.clientHeight,a=w/h,v=Math.max(8.5,11.5/a);camera.left=-v*a;camera.right=v*a;camera.top=v;camera.bottom=-v;camera.updateProjectionMatrix();renderer.setSize(w,h)};resize();const ro=new ResizeObserver(resize);ro.observe(host);
 let raf=0,last=performance.now();const loop=(now:number)=>{const dt=Math.min((now-last)/1000,.05);last=now;
 if(!control.current.paused&&!control.current.creator){
 gameTime+=dt*1.25;uiTime+=dt;for(let i=0;i<values.length;i++)values[i]=Math.max(0,values[i]-dt*[.16,.23,.13,.2,.18][i]);
 if(phase==='idle'){decisionIn-=dt;if(decisionIn<=0){const lowest=values.indexOf(Math.min(...values));command(['bed','eat','shower','tv','toilet'][lowest]);}}
 if(phase==='walking'){
 if(path.length){const d=path[0].clone().sub(person.position);d.y=0;const distance=d.length(),move=Math.min(distance,dt*1.65);if(distance<.02)path.shift();else{const next=person.position.clone().addScaledVector(d,move/distance);if(!blocked(next.x,next.z)){person.position.x=next.x;person.position.z=next.z;person.rotation.y=Math.atan2(d.x,d.z)}else{path=[];task='';phase='idle';decisionIn=2}}walkTime+=dt*8;legs[0].rotation.x=Math.sin(walkTime)*.45;legs[1].rotation.x=-Math.sin(walkTime)*.45;arms[0].rotation.x=-Math.sin(walkTime)*.35;arms[1].rotation.x=Math.sin(walkTime)*.35;
 }else{for(const limb of [...legs,...arms])limb.rotation.x=0;if(task){phase='using';elapsed=0;setAction(specs[task].label)}else{phase='idle';decisionIn=2;setAction('Descansando')}}}
 if(phase==='using'){
 const spec=specs[task];elapsed+=dt;const t=Math.min(1,elapsed/1.1);person.position.lerpVectors(spec.approach,spec.pose,t);
 if(task==='bed'){person.rotation.set(Math.PI/2*t,0,0);plumb.visible=false;}else if(task==='tv'||task==='toilet'){person.rotation.set(0,task==='tv'?Math.PI:0,0);legs.forEach(l=>l.rotation.x=-Math.PI/2*t);arms.forEach(l=>l.rotation.x=-.5*t);}else if(task==='shower'){arms[0].rotation.x=-1.7+Math.sin(elapsed*3)*.3;arms[1].rotation.x=-1.2-Math.sin(elapsed*3)*.3;}else if(task==='eat'){arms[1].rotation.x=-1.4+Math.sin(elapsed*2)*.3;}
 if(t===1)values[spec.need]=Math.min(100,values[spec.need]+dt*5);
 if(elapsed>=spec.duration){restore();task='';phase='idle';decisionIn=2;setAction('Descansando');}}
 drops.visible=phase==='using'&&task==='shower';if(drops.visible)for(const d of drops.children){d.position.y-=dt*3;if(d.position.y<.3)d.position.y=2.5}
 const watching=phase==='using'&&task==='tv';screenMat.emissive.setHSL((now/14000)%1,.5,watching?.4:0);screenMat.color.set(watching?0x79a7d3:0x17212b);
 if(uiTime>.3){uiTime=0;setNeeds([...initial,{name:'Vejiga',value:70,color:'#9aafdd',icon:'◉'}].map((n,i)=>({...n,value:values[i]})));const m=Math.floor(gameTime)%1440;setClock(String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0'));}
 }
 renderer.render(scene,camera);raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);
 return()=>{cancelAnimationFrame(raf);ro.disconnect();renderer.domElement.removeEventListener('pointerdown',click);actRef.current=()=>{};scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const m=Array.isArray(o.material)?o.material:[o.material];m.forEach(a=>a.dispose())}});renderer.dispose();host.removeChild(renderer.domElement)};
 },[avatar]);
 return <main className="game-shell"><div ref={mount} className="scene" aria-label="Habitación 3D interactiva"/><header className="topbar"><div className="brand"><span className="house">◆</span><div><b>CASA DE {avatar.name.toUpperCase()}</b><small>Martes · Primavera</small></div></div><div className="time"><button onClick={()=>setPaused(!paused)}>{paused?"▶":"Ⅱ"}</button><b>{clock}</b><div className="speed">▶ ▶ ▶</div></div><button className="menu" onClick={()=>setCreator(true)}>👤</button></header><aside className="needs"><div className="portrait"><span>◆</span><div className="avatar">{avatar.name[0]?.toUpperCase()}</div><div><b>{avatar.name}</b><small>{action}</small></div></div>{needs.map(n=><div className="need" key={n.name}><span>{n.icon}</span><div><label>{n.name}</label><i><em style={{width:`${n.value}%`,background:n.color}}/></i></div></div>)}</aside><div className="hint">Autonomía activa · Pulsa un mueble para darle una indicación</div><nav className="actions"><button onClick={()=>act("eat")}><span>◌</span>Comer</button><button onClick={()=>act("tv")}><span>▣</span>Televisión</button><button onClick={()=>act("bed")}><span>▰</span>Dormir</button><button onClick={()=>act("shower")}><span>♨</span>Ducha</button><button onClick={()=>act("toilet")}><span>◉</span>Baño</button></nav>{creator&&<div className="creator"><section><div className="creator-head"><div><small>CREAR PERSONAJE</small><h1>Tu nueva vida</h1></div>{!creator&&<button>×</button>}</div><label>Nombre<input value={avatar.name} onChange={e=>setAvatar({...avatar,name:e.target.value||"Alex"})}/></label><label>Complexión<select value={avatar.body} onChange={e=>setAvatar({...avatar,body:e.target.value})}><option>delgado</option><option>adulto</option><option>atlético</option></select></label><div className="swatches"><label>Piel<input type="color" value={avatar.skin} onChange={e=>setAvatar({...avatar,skin:e.target.value})}/></label><label>Cabello<input type="color" value={avatar.hair} onChange={e=>setAvatar({...avatar,hair:e.target.value})}/></label><label>Camisa<input type="color" value={avatar.shirt} onChange={e=>setAvatar({...avatar,shirt:e.target.value})}/></label><label>Pantalón<input type="color" value={avatar.pants} onChange={e=>setAvatar({...avatar,pants:e.target.value})}/></label></div><button className="play" onClick={()=>setCreator(false)}>ENTRAR A LA CASA</button></section></div>}</main>
}
